@c =============================================================================
@page
@node    MixerX
@chapter MixerX

It's an extended fork of the SDL_mixer library made by Vitaly Novichkov "Wohlstand"
in 13 January 2015. SDL_mixer is a quick and stable high-quality audio library,
however, it has own bunch of deffects and lack of certain abilities such
as inability to choose the MIDI backend in runtime, No support for cross-fade
and parallel streams playing (has only one musical stream. Using of very long
Chunks is ineffectively), etc. The goal of this fork is resolving those issues,
providing more extended functionality than was originally, and providing support
for more supported audio formats.

In this documentation, new-added functions, definitions, and enums in this fork
will be marked by @b{[Mixer X]} label. That means those functions are existing only
in SDL Mixer X fork and wasn't existed in original SDL_mixer library.

This fork is based on SDL_mixer 2.x unlike original documentation which is
created for SDL_mixer 1.2. Some functions would be marked by @b{[Mixer X]} label
which means those functions are not available in SDL_mixer 1.x, but available in
SDL_mixer 2.0 and SDL Mixer X fork.

@b{IMPORTANT}: The license for libADLMIDI, libOPNMIDI, libGME with MAME YM2612 emulator
is GPL which means that in order to use it your application must also be GPL!
