@c =============================================================================
@page
@node Getting Started
@chapter Getting Started

This assumes you have gotten SDL Mixer X and installed it on your system.
SDL_mixer has an INSTALL document in the source distribution to help you
get it compiled and installed.

@noindent
Generally, installation consists of:

@cartouche
@example
mkdir build
cd build
cmake ..
make
@end example
@end cartouche

@noindent
SDL Mixer X supports playing music and sound samples from the following formats:@*
- WAVE/RIFF (.wav)@*
- AIFF (.aiff)@*
- VOC (.voc)@*
- MOD (.mod .xm .s3m .669 .it .med and more) requiring libxmp or libmodplug @b{[Mixer 2.0]} built in package@*
- MIDI (.mid) using timidity, FluidSynth @b{[Mixer 2.0]}, libADLMIDI @b{[Mixer X]}, libOPNMIDI @b{[Mixer X]}, libEDMIDI @b{[Mixer X]} or native midi hardware@*
- OggVorbis (.ogg) requiring ogg/vorbis libraries built in package, or stb_vorbis enabled isntead@*
- MP3 (.mp3) requiring MPG123 library built in package, or DRMP3 enabled instead@*
- FLAC (.flac) requiring the FLAC library built in package, or DRFLAC enabled instead@*
- Opus (.opus) requiring the Opus/OpusFile library built in package@*
- GME (.spc .nsf .hes .vgm and more) requiring the libGME library built in package @b{[Mixer X]}@*
- also any command-line player, which is not mixed by SDL Mixer X...@*

@noindent
You may also want to look at some demonstration code which may be downloaded from:@*
@url{http://www.jonatkins.org/SDL_mixer/}

@menu
* Includes::    The include files to use for SDL_mixer
* Compiling::   Using the SDL_mixer library and header file.
@end menu

@c -----------------------------------------------------------------------------
@page
@node Includes
@section Includes

To use MixerX functions in a C/C++ source code file, you must use the
SDL_mixer_ext.h include file:

@cartouche
@code{  #include "SDL_mixer_ext.h"}
@end cartouche

@c -----------------------------------------------------------------------------
@page
@node Compiling
@section Compiling
@cindex sdl-config

To link with SDL MixerX you should use sdl-config to get the required SDL
compilation options. After that, compiling with MixerX is quite easy.@*
@b{Note}: Some systems may not have the SDL_mixer library and include file in the same place as the SDL library and includes are located, in that case you will need to add more -I and -L paths to these command lines.

@cartouche
Simple Example for compiling an object file:

@code{  cc -c `sdl2-config --cflags` mysource.c}

Simple Example for linking a program:

@code{  cc -o myprogram mysource.o `sdl2-config --libs` -lSDL2_mixer_ext}
@end cartouche

Now @command{myprogram} is ready to run.
