@c -----------------------------------------------------------------------------
@page
@c =============================================================================
@node Conflicts
@chapter Conflicts
@findex SDL_OpenAudio
@findex SDL_CloseAudio
@findex SDL_LockAudio
@findex SDL_UnlockAudio
@findex SDL_AudioDriverName
@findex SDL_GetAudioStatus
@findex SDL_PauseAudio

When using SDL_mixer functions you need to avoid the following functions from SDL:

@table @code
@item SDL_OpenAudio
Use @code{Mix_OpenAudio} instead.
@item SDL_CloseAudio
Use @code{Mix_CloseAudio} instead.
@item SDL_PauseAudio
@b{MIXER-X:}@*
Use @code{Mix_PauseAudio(0)} instead, to pause.@*
Use @code{Mix_PauseAudio(1)} instead, to pause.@*
@b{SDL_mixer:}@*
Use @code{Mix_Pause(-1)} and @code{Mix_PauseMusic} instead, to pause.@*
Use @code{Mix_Resume(-1)} and @code{Mix_ResumeMusic} instead, to unpause.
@item SDL_LockAudio
Use @code{Mix_LockAudio} instead.
@item SDL_UnlockAudio
Use @code{Mix_UnlockAudio} instead.
@end table

You may call the following functions freely:

@table @code
@item SDL_AudioDriverName
This will still work as usual.
@item SDL_GetAudioStatus
This will still work, though it will likely return @b{SDL_AUDIO_PLAYING}
even though SDL_mixer is just playing silence.
@end table

It is also a BAD idea to call SDL_mixer and SDL audio functions from a callback.
Callbacks include Effects functions and other SDL_mixer audio hooks.
