@c -----------------------------------------------------------------------------
@page
@c =============================================================================
@node Functions
@chapter Functions

These are the functions in the SDL_mixer API.

@menu
* General::   API activation
* Samples::   Loading sounds from files or memory
* Channels::  Sound effect channels
* Groups::    Sound effect channel grouping
* Music::     Music playing
* Effects::   Special effects processing
@end menu

@include 5_1_functions_general.texi
@include 5_2_functions_samples.texi
@include 5_3_functions_channels.texi
@include 5_4_functions_groups.texi
@include 5_5_functions_music.texi
@include 5_6_functions_effects.texi
