@c -----------------------------------------------------------------------------
@page
@c =============================================================================
@node Defines
@chapter Defines

@table @b
@cindex MIX_MAJOR_VERSION
@cindex SDL_MIXER_MAJOR_VERSION
@item SDL_MIXER_MAJOR_VERSION
@code{2}@*
SDL_mixer library major number at compilation time

@cindex MIX_MINOR_VERSION
@cindex SDL_MIXER_MINOR_VERSION
@item SDL_MIXER_MINOR_VERSION
@code{5}@*
SDL_mixer library minor number at compilation time

@item SDL_MIXER_PATCHLEVEL
@cindex MIX_PATCHLEVEL
@cindex SDL_MIXER_PATCHLEVEL
@code{0}@*
SDL_mixer library patch level at compilation time

@item SDL_MIXER_X
@cindex SDL_MIXER_X
@code{1}@*
Presense of this macro identifies the use of the MixerX extended fork library

@item MIX_CHANNELS
@cindex MIX_CHANNELS
@code{8}@*
The default mixer has this many simultaneous mixing channels after the first
call to @code{Mix_OpenAudio}.

@item MIX_DEFAULT_FREQUENCY
@cindex MIX_DEFAULT_FREQUENCY
@code{44100}@*
Good default sample rate in Hz (samples per second) for PC sound cards.

@item MIX_DEFAULT_FORMAT
@cindex MIX_DEFAULT_FORMAT
@code{AUDIO_S16SYS}@*
The suggested default is signed 16bit samples in host byte order.

@item MIX_DEFAULT_CHANNELS
@cindex MIX_DEFAULT_CHANNELS
@code{2}@*
Stereo sound is a good default.

@item MIX_MAX_VOLUME
@cindex MIX_MAX_VOLUME
@code{128}@*
Maximum value for any volume setting.@*
This is currently the same as @b{SDL_MIX_MAXVOLUME}.

@item MIX_CHANNEL_POST
@cindex MIX_CHANNEL_POST
@code{-2}@*
This is the channel number used for post processing effects.

@item MIX_EFFECTSMAXSPEED
@cindex MIX_EFFECTSMAXSPEED
@code{"MIX_EFFECTSMAXSPEED"}@*
A convience definition for the string name of the environment variable to define
when you desire the internal effects to sacrifice quality and/or RAM for speed.
The environment variable must be set (else nonexisting) before @code{Mix_OpenAudio}
is called for the setting to take effect.

@end table
