@c -----------------------------------------------------------------------------
@page
@c =============================================================================
@node Glossary
@chapter Glossary

@cartouche
@dfn{Byte Order}@*
@cindex Byte Order
@cindex MSB
@cindex LSB
@cindex Big-Endian
@cindex Little-Endian
Also known as @dfn{Big-Endian}.  Which means the most significant byte comes first in storage.  Sparc and Motorola 68k based chips are MSB ordered.@*
(SDL defines this as @b{SDL_BYTEORDER==SDL_BIG_ENDIAN})

@dfn{Little-Endian}(@acronym{LSB}) is stored in the opposite order, with the least significant byte first in memory.  Intel and AMD are two LSB machines.@*
(SDL defines this as @b{SDL_BYTEORDER==SDL_LIL_ENDIAN})
@end cartouche
