\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename SDL_mixer_ext.info
@settitle MixerX - the extended SDL_mixer
@c @setchapternewpage odd
@c @setcontentsaftertitlepage
@syncodeindex fn cp
@syncodeindex vr cp
@syncodeindex tp cp
@c %**end of header
@exampleindent 0
@ifinfo
This is an unofficial document for the SDL_mixer library API
and official for MixerX.

Copyright @copyright{} 2009 Jonathan Atkins (original documentation)
Copyright @copyright{} 2017-2021 Vitaliy Novichkov (MixerX specific updates)

Permission is granted to distribute freely, or in a distribution of any kind.
All distributions of this file must be in an unaltered state, except for corrections.

The latest copy of original document can be found at @url{http://www.jonatkins.org/SDL_mixer}
@end ifinfo

@titlepage
@sp 10
@title MixerX (an extended fork of SDL_mixer)

@subtitle @today{}

@author Jonathan Atkins
@page
@vskip 0pt plus 1filll
Copyright @copyright{} 2009 Jonathan Atkins (original documentation)
Copyright @copyright{} 2017-2021 Vitaliy Novichkov (MixerX specific updates)

Permission is granted to distribute freely, or in a distribution of any kind.
All distributions of this file must be in an unaltered state, except for corrections.

The latest copy of this document can be found at @url{http://www.jonatkins.org/SDL_mixer}
@end titlepage

@c @ifinfo
@c =============================================================================
@node    Top
@top MixerX

@menu
* Overview::         The README from the MixerX distribution

* MixerX::           About MixerX (a.k.a. SDL Mixer X) fork

* Getting Started::  Using SDL_mixer

* Conflicts::        Conflicts with SDL Audio functions

* Functions::        Functions supported by the SDL_mixer API
* Types::            Types used with the SDL_mixer API
* Defines::          Defined values/macros in the SDL_mixer API

* Glossary::         Terms used in this document

* Index::            Index of selected words
@end menu
@c @end ifinfo

@include 1_overview.texi
@include 2_mixerx.texi
@include 3_getting_started.texi
@include 4_conflicts.texi
@include 5_functions.texi
@include 6_types.texi
@include 7_defines.texi
@include 8_glossary.texi


@c -----------------------------------------------------------------------------
@page
@c =============================================================================
@contents

@c -----------------------------------------------------------------------------
@page
@c =============================================================================
@shortcontents

@c =============================================================================
@page
@node Index
@unnumbered Index

@printindex cp

@bye

