/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_srb2_nativecode_Main */

#ifndef _Included_org_srb2_nativecode_Main
#define _Included_org_srb2_nativecode_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_srb2_nativecode_Main
 * Method:    main
 * Signature: (Lorg/srb2/nativecode/Video;)I
 */
JNIEXPORT jint JNICALL Java_org_srb2_nativecode_Main_main
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
